---
- name: Install Jenkins with Java 17 on CentOS
  hosts: jenkins_servers
  become: yes

  tasks:
    - name: Ensure required packages are installed
      yum:
        name:
          - wget
          - git
          - curl
        state: present

    - name: Install Java 17 (OpenJDK)
      yum:
        name: java-17-openjdk
        state: present

    

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started
