---
- name: Install K3s on CentOS EC2
  hosts: k3s_servers
  become: yes

  vars:
    k3s_version: "v1.29.4+k3s1"   # specify version or leave empty for latest
    k3s_install_url: "https://get.k3s.io"

  tasks:
    - name: Install required packages
      yum:
        name:
          - curl
          - wget
          - iptables
        state: present

    - name: Disable SELinux (K3s needs this on CentOS)
      selinux:
        state: disabled

    - name: Download and install K3s
      shell: |
        curl -sfL {{ k3s_install_url }} | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Enable and start k3s service
      systemd:
        name: k3s
        enabled: yes
        state: started

    - name: Wait for node to be ready
      shell: "kubectl get nodes"
      register: kubectl_out
      retries: 10
      delay: 10
      until: "'Ready' in kubectl_out.stdout"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Create .kube directory for ec2-user
      file:
        path: /home/ec2-user/.kube
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy kubeconfig to ec2-user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ec2-user/.kube/config
        remote_src: yes
        owner: ec2-user
        group: ec2-user
        mode: '0600'